### PR TITLE
Resolved #13, Resolved #40, Resolved #41, Resolved #42, Resolved #43, Resolved #44, Resolved #45 - Implement CRUD Feature

### LINKED ISSUE #13: HTML/CSS for View Recipe Page

### LINKED ISSUE #40: Load data to my recipe section on landing page

### LINKED ISSUE #41: Load data to my recipes page

### LINKED ISSUE #42: Edit recipe feature
Load data to edit form when a user click edit from a recipe view

### LINKED ISSUE #43: View recipe feature
Load data to view form when a user clicks 'cook'

### LINKED ISSUE #44: Add recipe feature

### LINKED ISSUE #45: Delete recipe feature
Prompt user the confirmation page and then delete recipe when they click "yes" or go back to edit page when they click "no"

### PR DESCRIPTION
**Pull request by Kelvin1003**
Changelog: 
1. Implement the view recipe page
2. Implement the view feature for feature and favorite recipes

### CODE REVIEW

**Comment by Kelvin1003** [comment]
Changelog:
3. Implement jump to add page

**Comment by Kelvin1003** [comment]
Changelog:
4. Implement My recipes page
5. Control jump back to correct previous page

**Comment by tnl001** [comment]
remember to double quote

**Comment by Kelvin1003** [comment]
I will check all the issues after i implement all the crud feature.

**Comment by tnl001** [comment]
you can remove the add feature/button from the landing page. We'll only allow users to add when they are on the My Recipes page

**Comment by Kelvin1003** [comment]
I have spent time to implement this. I believe the UI designed by design group on MIro indicate users could add recipes when they are on the landing page

**Comment by tnl001** [comment]
oh in that case then you can keep it. It was something we thought about to make it less complicated to implement, but since you already did it, good job!

**Comment by Kelvin1003** [comment]
Changelog:
6. Implement Add Feature and All View Feature

**Comment by Kelvin1003** [comment]
Changelog:
8. Implement Edit Feature

**Comment by Kelvin1003** [comment]
ChangeLog:
9. Optimize the delete page
10. Implement Delete Feature

**Comment by Kelvin1003** [comment]
**CRUD DEMO is DONE!!**

I will solve all the issues tomorrow. I need to sleep lol.

**Pull request merged**
