### PR TITLE
Remove steps

### LINKED ISSUE #62: [BUG] Can't remove steps when creating/editing recipe
**Describe the bug**
User can't remove steps in procedures, only add.

**To Reproduce**
1. Go to landing page
2. Click on add symbol under 'Procedures'
3. See bug

**Expected behavior**
There should be another button to reduce the latest step, maybe just copy the add button and make it a minus?

**Screenshots**
image

### PR DESCRIPTION
**Pull request by puzonevan**
Fixes #62

### CODE REVIEW

**Comment by tnl001** [comment]
Still in-progress:
- same fix for add page component

**Comment by puzonevan** [comment]
@tnl001 finished add recipe remove buttons

**Comment by tnl001** [comment]
could u uncomment the fetches in main.js?

**Comment by puzonevan** [comment]
oops yeah keep forgetting to do that my bad. fixed

**Review by tnl001 — APPROVED** [review]

**Pull request merged**
